# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='companies',
            new_name='company',
        ),
    ]
