# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20170706_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
